// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

namespace api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("about");

                    b.Property<string>("adress");

                    b.Property<int>("age");

                    b.Property<string>("city");

                    b.Property<string>("company");

                    b.Property<string>("country");

                    b.Property<string>("degree");

                    b.Property<string>("email");

                    b.Property<string>("fullname");

                    b.Property<string>("gender");

                    b.Property<DateTime>("lastlogin");

                    b.Property<string>("linkedin");

                    b.Property<byte[]>("passwordhash");

                    b.Property<byte[]>("passwordsalt");

                    b.Property<int>("phone");

                    b.Property<string>("position");

                    b.Property<string>("profileicon");

                    b.Property<string>("qrcode");

                    b.Property<DateTime>("registed");

                    b.Property<string>("role");

                    b.Property<int>("schoolyear");

                    b.Property<string>("university");

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("api.Models.Value", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("id");

                    b.ToTable("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
