//MINHA API

export const GET_TEAM='GET_TEAM'
export const GET_INTERNAL_EVENTS ='GET_INTERNAL_EVENTS'
export const CREATE_TEAM='CREATE_TEAM'
export const DELETE_TEAM='DELETE_TEAM'
export const GET_CROMOS='GET_CROMOS'
export const GET_LOCS_VISITED= 'GET_LOCS_VISITED'
export const SCAN_QR = 'SCAN_QR'
export const LOGIN_INTERNAL ='LOGIN_INTERNAL'


//API BLUETREND

export const DATA_AVAILABLE = 'DATA_AVAILABLE';
export const API_LOGIN = 'API_LOGIN';
export const CHECK_USER='CHECK_USER';
export const LOGOUT_USER= 'LOGOUT_USER';
export const USER_INFO= 'USER_INFO'
export const HOLD='HOLD'
export const GET_EVENTS='GET_EVENTS'
export const UPDATE_USER='UPDATE_USER'
export const RESET_PASSWORD='RESET_PASSWORD'
export const CHECK_AND_RENEW='CHECK_AND_RENEW'
export const SESSION_DETAIL='SESSION_DETAIL'




//API BLUETREND CALENDÁRIO
export const GET_CAREERS='GET_CAREERS'  //GET GEST LISTS 
export const CHANGE_GUEST = 'CHANGE_GUEST'
export const GET_SESSIONS= 'GET_SESSIONS'
export const SIGN_SESSION= 'SIGN_SESSION'
export const WAIT_CHANGE='WAIT_CHANGE'
export const REMOVE_SESSION = 'REMOVE_SESSION'

//UI

//LOGIN
export const UI_LOGIN_RESET_PASSWORD= 'UI_LOGIN_RESET_PASSWORD'
export const UI_LOGIN_HELP_LOGIN='UI_LOGIN_HELP_LOGIN'
export const UI_LOGIN_PASSWORD_INPUT='UI_LOGIN_PASSWORD_INPUT'
export const UI_LOGIN_PASSWORD_INPUT_LOADING='UI_LOGIN_PASSWORD_INPUT_LOADING'
export const UI_LOGIN_PASSWORD_INPUT_INVALID='UI_LOGIN_PASSWORD_INPUT_INVALID'
export const UI_LOGIN_NOINTERNET='UI_LOGIN_NOINTERNET'
export const UI_LOGIN_OPEN_SCANNER='UI_LOIN_OPEN_SCANNER'
export const LOADINGLOGIN = 'LOADINGLOGIN'



export const OPEN_MODAL='OPEN_MODAL'
export const CLOSE_MODAL='CLOSE_MODAL'